services:
  nginx:
    image: knplabs/behat-training:nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/src/app/public
    ports:
      - 80:80

  php:
    image: knplabs/behat-training:php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app

  mysql:
    image: knplabs/behat-training:database
    build:
      context: ./docker/mysql
    environment:
      - MYSQL_DATABASE=behat-training
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - 'database:/var/lib/mysql'

  chrome:
    image: knplabs/behat-training:chrome
    build:
      context: ./docker/chrome
    ports:
      - 9222:9222

volumes:
  database: {}