services:
  nginx:
    image: knplabs/symfony-training:nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/src/app/public
    ports:
      - 80:80

  php:
    image: knplabs/symfony-training:php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app

  mysql:
    image: knplabs/symfony-training:database
    build:
      context: ./docker/mysql
    environment:
      - MYSQL_DATABASE=symfony-training
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - 'database:/var/lib/mysql'

volumes:
  database: {}